// Code generated by entc, DO NOT EDIT.

package theme

const (
	// Label holds the string label denoting the theme type in the database.
	Label = "theme"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrimary holds the string denoting the primary field in the database.
	FieldPrimary = "primary"
	// FieldSecondary holds the string denoting the secondary field in the database.
	FieldSecondary = "secondary"
	// EdgeList holds the string denoting the list edge name in mutations.
	EdgeList = "list"
	// Table holds the table name of the theme in the database.
	Table = "theme"
	// ListTable is the table that holds the list relation/edge.
	ListTable = "list"
	// ListInverseTable is the table name for the List entity.
	// It exists in this package in order to avoid circular dependency with the "list" package.
	ListInverseTable = "list"
	// ListColumn is the table column denoting the list relation/edge.
	ListColumn = "theme_id"
)

// Columns holds all SQL columns for theme fields.
var Columns = []string{
	FieldID,
	FieldPrimary,
	FieldSecondary,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
