version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ../gotrue/hack/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 10s

    expose: 
      - "5432"
  gotrue:
    image: supabase/gotrue:v2.6.36
    environment:
      - GOTRUE_SITE_URL="http://localhost:3000"
      - GOTRUE_JWT_SECRET=""
      - GOTRUE_DB_MIGRATIONS_PATH=/go/src/github.com/netlify/gotrue/migrations
      - GOTRUE_DB_DRIVER=postgres
      - DATABASE_URL=postgres://supabase_auth_admin:root@postgres:5432/postgres
      - GOTRUE_API_HOST=0.0.0.0
      - PORT=9999
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '9999:9999'
