// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: list.sql

package models

import (
	"context"
)

const checkListExist = `-- name: CheckListExist :one
SELECT EXISTS(SELECT 1 FROM list WHERE id =$1)
`

func (q *Queries) CheckListExist(ctx context.Context, id string) (bool, error) {
	row := q.queryRow(ctx, q.checkListExistStmt, checkListExist, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createList = `-- name: CreateList :exec
INSERT INTO list (id,name,theme_id) VALUES($1,$2,$3)
`

type CreateListParams struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	ThemeID int32  `json:"theme_id"`
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) error {
	_, err := q.exec(ctx, q.createListStmt, createList, arg.ID, arg.Name, arg.ThemeID)
	return err
}

const createTheme = `-- name: CreateTheme :one
INSERT INTO theme("primary",secondary)
    VALUES($1,$2) RETURNING id
`

type CreateThemeParams struct {
	Primary   string `json:"primary"`
	Secondary string `json:"secondary"`
}

func (q *Queries) CreateTheme(ctx context.Context, arg CreateThemeParams) (int32, error) {
	row := q.queryRow(ctx, q.createThemeStmt, createTheme, arg.Primary, arg.Secondary)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteList = `-- name: DeleteList :exec
UPDATE list SET is_deleted=true WHERE id=$1
`

func (q *Queries) DeleteList(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteListStmt, deleteList, id)
	return err
}

const findTheme = `-- name: FindTheme :one
SELECT id FROM theme WHERE "primary"=$1 AND secondary=$2
`

type FindThemeParams struct {
	Primary   string `json:"primary"`
	Secondary string `json:"secondary"`
}

func (q *Queries) FindTheme(ctx context.Context, arg FindThemeParams) (int32, error) {
	row := q.queryRow(ctx, q.findThemeStmt, findTheme, arg.Primary, arg.Secondary)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateList = `-- name: UpdateList :execrows
UPDATE list SET id=$1, name=$2, theme_id=$3 
    WHERE id=$1
`

type UpdateListParams struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	ThemeID int32  `json:"theme_id"`
}

func (q *Queries) UpdateList(ctx context.Context, arg UpdateListParams) (int64, error) {
	result, err := q.exec(ctx, q.updateListStmt, updateList, arg.ID, arg.Name, arg.ThemeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
