// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package models

import (
	"database/sql"
	"fmt"

	"github.com/tabbed/pqtype"
)

type RepeatEnum string

const (
	RepeatEnumDaily   RepeatEnum = "daily"
	RepeatEnumWeekly  RepeatEnum = "weekly"
	RepeatEnumMonthly RepeatEnum = "monthly"
)

func (e *RepeatEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RepeatEnum(s)
	case string:
		*e = RepeatEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for RepeatEnum: %T", src)
	}
	return nil
}

type List struct {
	ID           string
	Name         string
	ThemeID      int32
	LastModified sql.NullTime
}

type Task struct {
	ID           string
	Name         string
	Subtasks     pqtype.NullRawMessage
	ListID       string
	Description  sql.NullString
	Reminder     sql.NullTime
	Repeat       RepeatEnum
	IsCompleted  bool
	LastModified sql.NullTime
}

type Theme struct {
	ID        int32
	Primary   string
	Secondary string
}
