// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/iskaa02/taskkit-server/ent/migrate"

	"github.com/iskaa02/taskkit-server/ent/list"
	"github.com/iskaa02/taskkit-server/ent/task"
	"github.com/iskaa02/taskkit-server/ent/theme"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// List is the client for interacting with the List builders.
	List *ListClient
	// Task is the client for interacting with the Task builders.
	Task *TaskClient
	// Theme is the client for interacting with the Theme builders.
	Theme *ThemeClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.List = NewListClient(c.config)
	c.Task = NewTaskClient(c.config)
	c.Theme = NewThemeClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		List:   NewListClient(cfg),
		Task:   NewTaskClient(cfg),
		Theme:  NewThemeClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		List:   NewListClient(cfg),
		Task:   NewTaskClient(cfg),
		Theme:  NewThemeClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		List.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.List.Use(hooks...)
	c.Task.Use(hooks...)
	c.Theme.Use(hooks...)
}

// ListClient is a client for the List schema.
type ListClient struct {
	config
}

// NewListClient returns a client for the List from the given config.
func NewListClient(c config) *ListClient {
	return &ListClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `list.Hooks(f(g(h())))`.
func (c *ListClient) Use(hooks ...Hook) {
	c.hooks.List = append(c.hooks.List, hooks...)
}

// Create returns a create builder for List.
func (c *ListClient) Create() *ListCreate {
	mutation := newListMutation(c.config, OpCreate)
	return &ListCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of List entities.
func (c *ListClient) CreateBulk(builders ...*ListCreate) *ListCreateBulk {
	return &ListCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for List.
func (c *ListClient) Update() *ListUpdate {
	mutation := newListMutation(c.config, OpUpdate)
	return &ListUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ListClient) UpdateOne(l *List) *ListUpdateOne {
	mutation := newListMutation(c.config, OpUpdateOne, withList(l))
	return &ListUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ListClient) UpdateOneID(id string) *ListUpdateOne {
	mutation := newListMutation(c.config, OpUpdateOne, withListID(id))
	return &ListUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for List.
func (c *ListClient) Delete() *ListDelete {
	mutation := newListMutation(c.config, OpDelete)
	return &ListDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ListClient) DeleteOne(l *List) *ListDeleteOne {
	return c.DeleteOneID(l.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ListClient) DeleteOneID(id string) *ListDeleteOne {
	builder := c.Delete().Where(list.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ListDeleteOne{builder}
}

// Query returns a query builder for List.
func (c *ListClient) Query() *ListQuery {
	return &ListQuery{
		config: c.config,
	}
}

// Get returns a List entity by its id.
func (c *ListClient) Get(ctx context.Context, id string) (*List, error) {
	return c.Query().Where(list.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ListClient) GetX(ctx context.Context, id string) *List {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryTheme queries the theme edge of a List.
func (c *ListClient) QueryTheme(l *List) *ThemeQuery {
	query := &ThemeQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := l.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(list.Table, list.FieldID, id),
			sqlgraph.To(theme.Table, theme.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, list.ThemeTable, list.ThemeColumn),
		)
		fromV = sqlgraph.Neighbors(l.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTasks queries the tasks edge of a List.
func (c *ListClient) QueryTasks(l *List) *TaskQuery {
	query := &TaskQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := l.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(list.Table, list.FieldID, id),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, list.TasksTable, list.TasksColumn),
		)
		fromV = sqlgraph.Neighbors(l.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ListClient) Hooks() []Hook {
	return c.hooks.List
}

// TaskClient is a client for the Task schema.
type TaskClient struct {
	config
}

// NewTaskClient returns a client for the Task from the given config.
func NewTaskClient(c config) *TaskClient {
	return &TaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `task.Hooks(f(g(h())))`.
func (c *TaskClient) Use(hooks ...Hook) {
	c.hooks.Task = append(c.hooks.Task, hooks...)
}

// Create returns a create builder for Task.
func (c *TaskClient) Create() *TaskCreate {
	mutation := newTaskMutation(c.config, OpCreate)
	return &TaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Task entities.
func (c *TaskClient) CreateBulk(builders ...*TaskCreate) *TaskCreateBulk {
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Task.
func (c *TaskClient) Update() *TaskUpdate {
	mutation := newTaskMutation(c.config, OpUpdate)
	return &TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskClient) UpdateOne(t *Task) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTask(t))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskClient) UpdateOneID(id string) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTaskID(id))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Task.
func (c *TaskClient) Delete() *TaskDelete {
	mutation := newTaskMutation(c.config, OpDelete)
	return &TaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *TaskClient) DeleteOne(t *Task) *TaskDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *TaskClient) DeleteOneID(id string) *TaskDeleteOne {
	builder := c.Delete().Where(task.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskDeleteOne{builder}
}

// Query returns a query builder for Task.
func (c *TaskClient) Query() *TaskQuery {
	return &TaskQuery{
		config: c.config,
	}
}

// Get returns a Task entity by its id.
func (c *TaskClient) Get(ctx context.Context, id string) (*Task, error) {
	return c.Query().Where(task.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskClient) GetX(ctx context.Context, id string) *Task {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryList queries the list edge of a Task.
func (c *TaskClient) QueryList(t *Task) *ListQuery {
	query := &ListQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(task.Table, task.FieldID, id),
			sqlgraph.To(list.Table, list.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, task.ListTable, task.ListColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TaskClient) Hooks() []Hook {
	return c.hooks.Task
}

// ThemeClient is a client for the Theme schema.
type ThemeClient struct {
	config
}

// NewThemeClient returns a client for the Theme from the given config.
func NewThemeClient(c config) *ThemeClient {
	return &ThemeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `theme.Hooks(f(g(h())))`.
func (c *ThemeClient) Use(hooks ...Hook) {
	c.hooks.Theme = append(c.hooks.Theme, hooks...)
}

// Create returns a create builder for Theme.
func (c *ThemeClient) Create() *ThemeCreate {
	mutation := newThemeMutation(c.config, OpCreate)
	return &ThemeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Theme entities.
func (c *ThemeClient) CreateBulk(builders ...*ThemeCreate) *ThemeCreateBulk {
	return &ThemeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Theme.
func (c *ThemeClient) Update() *ThemeUpdate {
	mutation := newThemeMutation(c.config, OpUpdate)
	return &ThemeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ThemeClient) UpdateOne(t *Theme) *ThemeUpdateOne {
	mutation := newThemeMutation(c.config, OpUpdateOne, withTheme(t))
	return &ThemeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ThemeClient) UpdateOneID(id int64) *ThemeUpdateOne {
	mutation := newThemeMutation(c.config, OpUpdateOne, withThemeID(id))
	return &ThemeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Theme.
func (c *ThemeClient) Delete() *ThemeDelete {
	mutation := newThemeMutation(c.config, OpDelete)
	return &ThemeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ThemeClient) DeleteOne(t *Theme) *ThemeDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ThemeClient) DeleteOneID(id int64) *ThemeDeleteOne {
	builder := c.Delete().Where(theme.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ThemeDeleteOne{builder}
}

// Query returns a query builder for Theme.
func (c *ThemeClient) Query() *ThemeQuery {
	return &ThemeQuery{
		config: c.config,
	}
}

// Get returns a Theme entity by its id.
func (c *ThemeClient) Get(ctx context.Context, id int64) (*Theme, error) {
	return c.Query().Where(theme.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ThemeClient) GetX(ctx context.Context, id int64) *Theme {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryLists queries the lists edge of a Theme.
func (c *ThemeClient) QueryLists(t *Theme) *ListQuery {
	query := &ListQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(theme.Table, theme.FieldID, id),
			sqlgraph.To(list.Table, list.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, theme.ListsTable, theme.ListsColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ThemeClient) Hooks() []Hook {
	return c.hooks.Theme
}
