// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iskaa02/taskkit-server/ent/list"
	"github.com/iskaa02/taskkit-server/ent/task"
	"github.com/iskaa02/taskkit-server/ent/theme"
)

// ListCreate is the builder for creating a List entity.
type ListCreate struct {
	config
	mutation *ListMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (lc *ListCreate) SetName(s string) *ListCreate {
	lc.mutation.SetName(s)
	return lc
}

// SetThemeID sets the "theme_id" field.
func (lc *ListCreate) SetThemeID(i int64) *ListCreate {
	lc.mutation.SetThemeID(i)
	return lc
}

// SetIsDeleted sets the "is_deleted" field.
func (lc *ListCreate) SetIsDeleted(b bool) *ListCreate {
	lc.mutation.SetIsDeleted(b)
	return lc
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (lc *ListCreate) SetNillableIsDeleted(b *bool) *ListCreate {
	if b != nil {
		lc.SetIsDeleted(*b)
	}
	return lc
}

// SetLastModified sets the "last_modified" field.
func (lc *ListCreate) SetLastModified(t time.Time) *ListCreate {
	lc.mutation.SetLastModified(t)
	return lc
}

// SetNillableLastModified sets the "last_modified" field if the given value is not nil.
func (lc *ListCreate) SetNillableLastModified(t *time.Time) *ListCreate {
	if t != nil {
		lc.SetLastModified(*t)
	}
	return lc
}

// SetCreatedAt sets the "created_at" field.
func (lc *ListCreate) SetCreatedAt(t time.Time) *ListCreate {
	lc.mutation.SetCreatedAt(t)
	return lc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (lc *ListCreate) SetNillableCreatedAt(t *time.Time) *ListCreate {
	if t != nil {
		lc.SetCreatedAt(*t)
	}
	return lc
}

// SetID sets the "id" field.
func (lc *ListCreate) SetID(s string) *ListCreate {
	lc.mutation.SetID(s)
	return lc
}

// SetTheme sets the "theme" edge to the Theme entity.
func (lc *ListCreate) SetTheme(t *Theme) *ListCreate {
	return lc.SetThemeID(t.ID)
}

// AddTaskIDs adds the "task" edge to the Task entity by IDs.
func (lc *ListCreate) AddTaskIDs(ids ...string) *ListCreate {
	lc.mutation.AddTaskIDs(ids...)
	return lc
}

// AddTask adds the "task" edges to the Task entity.
func (lc *ListCreate) AddTask(t ...*Task) *ListCreate {
	ids := make([]string, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return lc.AddTaskIDs(ids...)
}

// Mutation returns the ListMutation object of the builder.
func (lc *ListCreate) Mutation() *ListMutation {
	return lc.mutation
}

// Save creates the List in the database.
func (lc *ListCreate) Save(ctx context.Context) (*List, error) {
	var (
		err  error
		node *List
	)
	lc.defaults()
	if len(lc.hooks) == 0 {
		if err = lc.check(); err != nil {
			return nil, err
		}
		node, err = lc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ListMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = lc.check(); err != nil {
				return nil, err
			}
			lc.mutation = mutation
			if node, err = lc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(lc.hooks) - 1; i >= 0; i-- {
			if lc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (lc *ListCreate) SaveX(ctx context.Context) *List {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *ListCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *ListCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lc *ListCreate) defaults() {
	if _, ok := lc.mutation.IsDeleted(); !ok {
		v := list.DefaultIsDeleted
		lc.mutation.SetIsDeleted(v)
	}
	if _, ok := lc.mutation.LastModified(); !ok {
		v := list.DefaultLastModified
		lc.mutation.SetLastModified(v)
	}
	if _, ok := lc.mutation.CreatedAt(); !ok {
		v := list.DefaultCreatedAt
		lc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *ListCreate) check() error {
	if _, ok := lc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "List.name"`)}
	}
	if _, ok := lc.mutation.ThemeID(); !ok {
		return &ValidationError{Name: "theme_id", err: errors.New(`ent: missing required field "List.theme_id"`)}
	}
	if _, ok := lc.mutation.IsDeleted(); !ok {
		return &ValidationError{Name: "is_deleted", err: errors.New(`ent: missing required field "List.is_deleted"`)}
	}
	if _, ok := lc.mutation.LastModified(); !ok {
		return &ValidationError{Name: "last_modified", err: errors.New(`ent: missing required field "List.last_modified"`)}
	}
	if _, ok := lc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "List.created_at"`)}
	}
	if _, ok := lc.mutation.ThemeID(); !ok {
		return &ValidationError{Name: "theme", err: errors.New(`ent: missing required edge "List.theme"`)}
	}
	return nil
}

func (lc *ListCreate) sqlSave(ctx context.Context) (*List, error) {
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected List.ID type: %T", _spec.ID.Value)
		}
	}
	return _node, nil
}

func (lc *ListCreate) createSpec() (*List, *sqlgraph.CreateSpec) {
	var (
		_node = &List{config: lc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: list.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: list.FieldID,
			},
		}
	)
	if id, ok := lc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := lc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: list.FieldName,
		})
		_node.Name = value
	}
	if value, ok := lc.mutation.IsDeleted(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: list.FieldIsDeleted,
		})
		_node.IsDeleted = value
	}
	if value, ok := lc.mutation.LastModified(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: list.FieldLastModified,
		})
		_node.LastModified = value
	}
	if value, ok := lc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: list.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if nodes := lc.mutation.ThemeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   list.ThemeTable,
			Columns: []string{list.ThemeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: theme.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ThemeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := lc.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   list.TaskTable,
			Columns: []string{list.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: task.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ListCreateBulk is the builder for creating many List entities in bulk.
type ListCreateBulk struct {
	config
	builders []*ListCreate
}

// Save creates the List entities in the database.
func (lcb *ListCreateBulk) Save(ctx context.Context) ([]*List, error) {
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*List, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ListMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *ListCreateBulk) SaveX(ctx context.Context) []*List {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *ListCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *ListCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}
