// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/iskaa02/taskkit-server/ent/list"
	"github.com/iskaa02/taskkit-server/ent/schema"
	"github.com/iskaa02/taskkit-server/ent/task"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	listFields := schema.List{}.Fields()
	_ = listFields
	// listDescIsDeleted is the schema descriptor for is_deleted field.
	listDescIsDeleted := listFields[3].Descriptor()
	// list.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	list.DefaultIsDeleted = listDescIsDeleted.Default.(bool)
	// listDescLastModified is the schema descriptor for last_modified field.
	listDescLastModified := listFields[4].Descriptor()
	// list.DefaultLastModified holds the default value on creation for the last_modified field.
	list.DefaultLastModified = listDescLastModified.Default.(time.Time)
	// listDescCreatedAt is the schema descriptor for created_at field.
	listDescCreatedAt := listFields[5].Descriptor()
	// list.DefaultCreatedAt holds the default value on creation for the created_at field.
	list.DefaultCreatedAt = listDescCreatedAt.Default.(time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescIsCompleted is the schema descriptor for is_completed field.
	taskDescIsCompleted := taskFields[7].Descriptor()
	// task.DefaultIsCompleted holds the default value on creation for the is_completed field.
	task.DefaultIsCompleted = taskDescIsCompleted.Default.(bool)
	// taskDescIsDeleted is the schema descriptor for is_deleted field.
	taskDescIsDeleted := taskFields[8].Descriptor()
	// task.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	task.DefaultIsDeleted = taskDescIsDeleted.Default.(bool)
	// taskDescLastModified is the schema descriptor for last_modified field.
	taskDescLastModified := taskFields[9].Descriptor()
	// task.DefaultLastModified holds the default value on creation for the last_modified field.
	task.DefaultLastModified = taskDescLastModified.Default.(func() time.Time)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[10].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
}
