// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iskaa02/taskkit-server/ent/list"
	"github.com/iskaa02/taskkit-server/ent/predicate"
	"github.com/iskaa02/taskkit-server/ent/task"
	"github.com/iskaa02/taskkit-server/types"
	"gopkg.in/guregu/null.v4"
)

// TaskUpdate is the builder for updating Task entities.
type TaskUpdate struct {
	config
	hooks    []Hook
	mutation *TaskMutation
}

// Where appends a list predicates to the TaskUpdate builder.
func (tu *TaskUpdate) Where(ps ...predicate.Task) *TaskUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetName sets the "name" field.
func (tu *TaskUpdate) SetName(s string) *TaskUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetListID sets the "list_id" field.
func (tu *TaskUpdate) SetListID(s string) *TaskUpdate {
	tu.mutation.SetListID(s)
	return tu
}

// SetDescription sets the "description" field.
func (tu *TaskUpdate) SetDescription(n null.String) *TaskUpdate {
	tu.mutation.SetDescription(n)
	return tu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableDescription(n *null.String) *TaskUpdate {
	if n != nil {
		tu.SetDescription(*n)
	}
	return tu
}

// ClearDescription clears the value of the "description" field.
func (tu *TaskUpdate) ClearDescription() *TaskUpdate {
	tu.mutation.ClearDescription()
	return tu
}

// SetReminder sets the "reminder" field.
func (tu *TaskUpdate) SetReminder(n null.Time) *TaskUpdate {
	tu.mutation.SetReminder(n)
	return tu
}

// SetNillableReminder sets the "reminder" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableReminder(n *null.Time) *TaskUpdate {
	if n != nil {
		tu.SetReminder(*n)
	}
	return tu
}

// ClearReminder clears the value of the "reminder" field.
func (tu *TaskUpdate) ClearReminder() *TaskUpdate {
	tu.mutation.ClearReminder()
	return tu
}

// SetRepeat sets the "repeat" field.
func (tu *TaskUpdate) SetRepeat(n null.String) *TaskUpdate {
	tu.mutation.SetRepeat(n)
	return tu
}

// SetNillableRepeat sets the "repeat" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableRepeat(n *null.String) *TaskUpdate {
	if n != nil {
		tu.SetRepeat(*n)
	}
	return tu
}

// ClearRepeat clears the value of the "repeat" field.
func (tu *TaskUpdate) ClearRepeat() *TaskUpdate {
	tu.mutation.ClearRepeat()
	return tu
}

// SetSubtasks sets the "subtasks" field.
func (tu *TaskUpdate) SetSubtasks(t *types.Subtasks) *TaskUpdate {
	tu.mutation.SetSubtasks(t)
	return tu
}

// SetIsCompleted sets the "is_completed" field.
func (tu *TaskUpdate) SetIsCompleted(b bool) *TaskUpdate {
	tu.mutation.SetIsCompleted(b)
	return tu
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableIsCompleted(b *bool) *TaskUpdate {
	if b != nil {
		tu.SetIsCompleted(*b)
	}
	return tu
}

// SetIsDeleted sets the "is_deleted" field.
func (tu *TaskUpdate) SetIsDeleted(b bool) *TaskUpdate {
	tu.mutation.SetIsDeleted(b)
	return tu
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableIsDeleted(b *bool) *TaskUpdate {
	if b != nil {
		tu.SetIsDeleted(*b)
	}
	return tu
}

// SetLastModified sets the "last_modified" field.
func (tu *TaskUpdate) SetLastModified(t time.Time) *TaskUpdate {
	tu.mutation.SetLastModified(t)
	return tu
}

// SetNillableLastModified sets the "last_modified" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableLastModified(t *time.Time) *TaskUpdate {
	if t != nil {
		tu.SetLastModified(*t)
	}
	return tu
}

// SetCreatedAt sets the "created_at" field.
func (tu *TaskUpdate) SetCreatedAt(t time.Time) *TaskUpdate {
	tu.mutation.SetCreatedAt(t)
	return tu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tu *TaskUpdate) SetNillableCreatedAt(t *time.Time) *TaskUpdate {
	if t != nil {
		tu.SetCreatedAt(*t)
	}
	return tu
}

// SetList sets the "list" edge to the List entity.
func (tu *TaskUpdate) SetList(l *List) *TaskUpdate {
	return tu.SetListID(l.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (tu *TaskUpdate) Mutation() *TaskMutation {
	return tu.mutation
}

// ClearList clears the "list" edge to the List entity.
func (tu *TaskUpdate) ClearList() *TaskUpdate {
	tu.mutation.ClearList()
	return tu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TaskUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tu.hooks) == 0 {
		if err = tu.check(); err != nil {
			return 0, err
		}
		affected, err = tu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TaskMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tu.check(); err != nil {
				return 0, err
			}
			tu.mutation = mutation
			affected, err = tu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tu.hooks) - 1; i >= 0; i-- {
			if tu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TaskUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TaskUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TaskUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TaskUpdate) check() error {
	if _, ok := tu.mutation.ListID(); tu.mutation.ListCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Task.list"`)
	}
	return nil
}

func (tu *TaskUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   task.Table,
			Columns: task.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: task.FieldID,
			},
		},
	}
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: task.FieldName,
		})
	}
	if value, ok := tu.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: task.FieldDescription,
		})
	}
	if tu.mutation.DescriptionCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: task.FieldDescription,
		})
	}
	if value, ok := tu.mutation.Reminder(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: task.FieldReminder,
		})
	}
	if tu.mutation.ReminderCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: task.FieldReminder,
		})
	}
	if value, ok := tu.mutation.Repeat(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: task.FieldRepeat,
		})
	}
	if tu.mutation.RepeatCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: task.FieldRepeat,
		})
	}
	if value, ok := tu.mutation.Subtasks(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: task.FieldSubtasks,
		})
	}
	if value, ok := tu.mutation.IsCompleted(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: task.FieldIsCompleted,
		})
	}
	if value, ok := tu.mutation.IsDeleted(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: task.FieldIsDeleted,
		})
	}
	if value, ok := tu.mutation.LastModified(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: task.FieldLastModified,
		})
	}
	if value, ok := tu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: task.FieldCreatedAt,
		})
	}
	if tu.mutation.ListCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ListTable,
			Columns: []string{task.ListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: list.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.ListIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ListTable,
			Columns: []string{task.ListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: list.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// TaskUpdateOne is the builder for updating a single Task entity.
type TaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskMutation
}

// SetName sets the "name" field.
func (tuo *TaskUpdateOne) SetName(s string) *TaskUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetListID sets the "list_id" field.
func (tuo *TaskUpdateOne) SetListID(s string) *TaskUpdateOne {
	tuo.mutation.SetListID(s)
	return tuo
}

// SetDescription sets the "description" field.
func (tuo *TaskUpdateOne) SetDescription(n null.String) *TaskUpdateOne {
	tuo.mutation.SetDescription(n)
	return tuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableDescription(n *null.String) *TaskUpdateOne {
	if n != nil {
		tuo.SetDescription(*n)
	}
	return tuo
}

// ClearDescription clears the value of the "description" field.
func (tuo *TaskUpdateOne) ClearDescription() *TaskUpdateOne {
	tuo.mutation.ClearDescription()
	return tuo
}

// SetReminder sets the "reminder" field.
func (tuo *TaskUpdateOne) SetReminder(n null.Time) *TaskUpdateOne {
	tuo.mutation.SetReminder(n)
	return tuo
}

// SetNillableReminder sets the "reminder" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableReminder(n *null.Time) *TaskUpdateOne {
	if n != nil {
		tuo.SetReminder(*n)
	}
	return tuo
}

// ClearReminder clears the value of the "reminder" field.
func (tuo *TaskUpdateOne) ClearReminder() *TaskUpdateOne {
	tuo.mutation.ClearReminder()
	return tuo
}

// SetRepeat sets the "repeat" field.
func (tuo *TaskUpdateOne) SetRepeat(n null.String) *TaskUpdateOne {
	tuo.mutation.SetRepeat(n)
	return tuo
}

// SetNillableRepeat sets the "repeat" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableRepeat(n *null.String) *TaskUpdateOne {
	if n != nil {
		tuo.SetRepeat(*n)
	}
	return tuo
}

// ClearRepeat clears the value of the "repeat" field.
func (tuo *TaskUpdateOne) ClearRepeat() *TaskUpdateOne {
	tuo.mutation.ClearRepeat()
	return tuo
}

// SetSubtasks sets the "subtasks" field.
func (tuo *TaskUpdateOne) SetSubtasks(t *types.Subtasks) *TaskUpdateOne {
	tuo.mutation.SetSubtasks(t)
	return tuo
}

// SetIsCompleted sets the "is_completed" field.
func (tuo *TaskUpdateOne) SetIsCompleted(b bool) *TaskUpdateOne {
	tuo.mutation.SetIsCompleted(b)
	return tuo
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableIsCompleted(b *bool) *TaskUpdateOne {
	if b != nil {
		tuo.SetIsCompleted(*b)
	}
	return tuo
}

// SetIsDeleted sets the "is_deleted" field.
func (tuo *TaskUpdateOne) SetIsDeleted(b bool) *TaskUpdateOne {
	tuo.mutation.SetIsDeleted(b)
	return tuo
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableIsDeleted(b *bool) *TaskUpdateOne {
	if b != nil {
		tuo.SetIsDeleted(*b)
	}
	return tuo
}

// SetLastModified sets the "last_modified" field.
func (tuo *TaskUpdateOne) SetLastModified(t time.Time) *TaskUpdateOne {
	tuo.mutation.SetLastModified(t)
	return tuo
}

// SetNillableLastModified sets the "last_modified" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableLastModified(t *time.Time) *TaskUpdateOne {
	if t != nil {
		tuo.SetLastModified(*t)
	}
	return tuo
}

// SetCreatedAt sets the "created_at" field.
func (tuo *TaskUpdateOne) SetCreatedAt(t time.Time) *TaskUpdateOne {
	tuo.mutation.SetCreatedAt(t)
	return tuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tuo *TaskUpdateOne) SetNillableCreatedAt(t *time.Time) *TaskUpdateOne {
	if t != nil {
		tuo.SetCreatedAt(*t)
	}
	return tuo
}

// SetList sets the "list" edge to the List entity.
func (tuo *TaskUpdateOne) SetList(l *List) *TaskUpdateOne {
	return tuo.SetListID(l.ID)
}

// Mutation returns the TaskMutation object of the builder.
func (tuo *TaskUpdateOne) Mutation() *TaskMutation {
	return tuo.mutation
}

// ClearList clears the "list" edge to the List entity.
func (tuo *TaskUpdateOne) ClearList() *TaskUpdateOne {
	tuo.mutation.ClearList()
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TaskUpdateOne) Select(field string, fields ...string) *TaskUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Task entity.
func (tuo *TaskUpdateOne) Save(ctx context.Context) (*Task, error) {
	var (
		err  error
		node *Task
	)
	if len(tuo.hooks) == 0 {
		if err = tuo.check(); err != nil {
			return nil, err
		}
		node, err = tuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TaskMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tuo.check(); err != nil {
				return nil, err
			}
			tuo.mutation = mutation
			node, err = tuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tuo.hooks) - 1; i >= 0; i-- {
			if tuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TaskUpdateOne) SaveX(ctx context.Context) *Task {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TaskUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TaskUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TaskUpdateOne) check() error {
	if _, ok := tuo.mutation.ListID(); tuo.mutation.ListCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Task.list"`)
	}
	return nil
}

func (tuo *TaskUpdateOne) sqlSave(ctx context.Context) (_node *Task, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   task.Table,
			Columns: task.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: task.FieldID,
			},
		},
	}
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Task.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, task.FieldID)
		for _, f := range fields {
			if !task.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != task.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: task.FieldName,
		})
	}
	if value, ok := tuo.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: task.FieldDescription,
		})
	}
	if tuo.mutation.DescriptionCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: task.FieldDescription,
		})
	}
	if value, ok := tuo.mutation.Reminder(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: task.FieldReminder,
		})
	}
	if tuo.mutation.ReminderCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: task.FieldReminder,
		})
	}
	if value, ok := tuo.mutation.Repeat(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: task.FieldRepeat,
		})
	}
	if tuo.mutation.RepeatCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: task.FieldRepeat,
		})
	}
	if value, ok := tuo.mutation.Subtasks(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: task.FieldSubtasks,
		})
	}
	if value, ok := tuo.mutation.IsCompleted(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: task.FieldIsCompleted,
		})
	}
	if value, ok := tuo.mutation.IsDeleted(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: task.FieldIsDeleted,
		})
	}
	if value, ok := tuo.mutation.LastModified(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: task.FieldLastModified,
		})
	}
	if value, ok := tuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: task.FieldCreatedAt,
		})
	}
	if tuo.mutation.ListCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ListTable,
			Columns: []string{task.ListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: list.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.ListIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   task.ListTable,
			Columns: []string{task.ListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: list.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Task{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{task.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
