// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/iskaa02/taskkit-server/ent/list"
	"github.com/iskaa02/taskkit-server/ent/predicate"
	"github.com/iskaa02/taskkit-server/ent/theme"
	"gopkg.in/guregu/null.v4"
)

// ThemeUpdate is the builder for updating Theme entities.
type ThemeUpdate struct {
	config
	hooks    []Hook
	mutation *ThemeMutation
}

// Where appends a list predicates to the ThemeUpdate builder.
func (tu *ThemeUpdate) Where(ps ...predicate.Theme) *ThemeUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetPrimary sets the "primary" field.
func (tu *ThemeUpdate) SetPrimary(s string) *ThemeUpdate {
	tu.mutation.SetPrimary(s)
	return tu
}

// SetSecondary sets the "secondary" field.
func (tu *ThemeUpdate) SetSecondary(n null.String) *ThemeUpdate {
	tu.mutation.SetSecondary(n)
	return tu
}

// SetNillableSecondary sets the "secondary" field if the given value is not nil.
func (tu *ThemeUpdate) SetNillableSecondary(n *null.String) *ThemeUpdate {
	if n != nil {
		tu.SetSecondary(*n)
	}
	return tu
}

// ClearSecondary clears the value of the "secondary" field.
func (tu *ThemeUpdate) ClearSecondary() *ThemeUpdate {
	tu.mutation.ClearSecondary()
	return tu
}

// AddListIDs adds the "list" edge to the List entity by IDs.
func (tu *ThemeUpdate) AddListIDs(ids ...string) *ThemeUpdate {
	tu.mutation.AddListIDs(ids...)
	return tu
}

// AddList adds the "list" edges to the List entity.
func (tu *ThemeUpdate) AddList(l ...*List) *ThemeUpdate {
	ids := make([]string, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return tu.AddListIDs(ids...)
}

// Mutation returns the ThemeMutation object of the builder.
func (tu *ThemeUpdate) Mutation() *ThemeMutation {
	return tu.mutation
}

// ClearList clears all "list" edges to the List entity.
func (tu *ThemeUpdate) ClearList() *ThemeUpdate {
	tu.mutation.ClearList()
	return tu
}

// RemoveListIDs removes the "list" edge to List entities by IDs.
func (tu *ThemeUpdate) RemoveListIDs(ids ...string) *ThemeUpdate {
	tu.mutation.RemoveListIDs(ids...)
	return tu
}

// RemoveList removes "list" edges to List entities.
func (tu *ThemeUpdate) RemoveList(l ...*List) *ThemeUpdate {
	ids := make([]string, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return tu.RemoveListIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *ThemeUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tu.hooks) == 0 {
		affected, err = tu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ThemeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tu.mutation = mutation
			affected, err = tu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tu.hooks) - 1; i >= 0; i-- {
			if tu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tu *ThemeUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *ThemeUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *ThemeUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *ThemeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   theme.Table,
			Columns: theme.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: theme.FieldID,
			},
		},
	}
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Primary(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: theme.FieldPrimary,
		})
	}
	if value, ok := tu.mutation.Secondary(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: theme.FieldSecondary,
		})
	}
	if tu.mutation.SecondaryCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: theme.FieldSecondary,
		})
	}
	if tu.mutation.ListCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theme.ListTable,
			Columns: []string{theme.ListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: list.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedListIDs(); len(nodes) > 0 && !tu.mutation.ListCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theme.ListTable,
			Columns: []string{theme.ListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: list.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.ListIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theme.ListTable,
			Columns: []string{theme.ListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: list.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{theme.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// ThemeUpdateOne is the builder for updating a single Theme entity.
type ThemeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ThemeMutation
}

// SetPrimary sets the "primary" field.
func (tuo *ThemeUpdateOne) SetPrimary(s string) *ThemeUpdateOne {
	tuo.mutation.SetPrimary(s)
	return tuo
}

// SetSecondary sets the "secondary" field.
func (tuo *ThemeUpdateOne) SetSecondary(n null.String) *ThemeUpdateOne {
	tuo.mutation.SetSecondary(n)
	return tuo
}

// SetNillableSecondary sets the "secondary" field if the given value is not nil.
func (tuo *ThemeUpdateOne) SetNillableSecondary(n *null.String) *ThemeUpdateOne {
	if n != nil {
		tuo.SetSecondary(*n)
	}
	return tuo
}

// ClearSecondary clears the value of the "secondary" field.
func (tuo *ThemeUpdateOne) ClearSecondary() *ThemeUpdateOne {
	tuo.mutation.ClearSecondary()
	return tuo
}

// AddListIDs adds the "list" edge to the List entity by IDs.
func (tuo *ThemeUpdateOne) AddListIDs(ids ...string) *ThemeUpdateOne {
	tuo.mutation.AddListIDs(ids...)
	return tuo
}

// AddList adds the "list" edges to the List entity.
func (tuo *ThemeUpdateOne) AddList(l ...*List) *ThemeUpdateOne {
	ids := make([]string, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return tuo.AddListIDs(ids...)
}

// Mutation returns the ThemeMutation object of the builder.
func (tuo *ThemeUpdateOne) Mutation() *ThemeMutation {
	return tuo.mutation
}

// ClearList clears all "list" edges to the List entity.
func (tuo *ThemeUpdateOne) ClearList() *ThemeUpdateOne {
	tuo.mutation.ClearList()
	return tuo
}

// RemoveListIDs removes the "list" edge to List entities by IDs.
func (tuo *ThemeUpdateOne) RemoveListIDs(ids ...string) *ThemeUpdateOne {
	tuo.mutation.RemoveListIDs(ids...)
	return tuo
}

// RemoveList removes "list" edges to List entities.
func (tuo *ThemeUpdateOne) RemoveList(l ...*List) *ThemeUpdateOne {
	ids := make([]string, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return tuo.RemoveListIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *ThemeUpdateOne) Select(field string, fields ...string) *ThemeUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Theme entity.
func (tuo *ThemeUpdateOne) Save(ctx context.Context) (*Theme, error) {
	var (
		err  error
		node *Theme
	)
	if len(tuo.hooks) == 0 {
		node, err = tuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ThemeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tuo.mutation = mutation
			node, err = tuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tuo.hooks) - 1; i >= 0; i-- {
			if tuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *ThemeUpdateOne) SaveX(ctx context.Context) *Theme {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *ThemeUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *ThemeUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *ThemeUpdateOne) sqlSave(ctx context.Context) (_node *Theme, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   theme.Table,
			Columns: theme.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: theme.FieldID,
			},
		},
	}
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Theme.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, theme.FieldID)
		for _, f := range fields {
			if !theme.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != theme.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Primary(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: theme.FieldPrimary,
		})
	}
	if value, ok := tuo.mutation.Secondary(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: theme.FieldSecondary,
		})
	}
	if tuo.mutation.SecondaryCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: theme.FieldSecondary,
		})
	}
	if tuo.mutation.ListCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theme.ListTable,
			Columns: []string{theme.ListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: list.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedListIDs(); len(nodes) > 0 && !tuo.mutation.ListCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theme.ListTable,
			Columns: []string{theme.ListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: list.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.ListIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theme.ListTable,
			Columns: []string{theme.ListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: list.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Theme{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{theme.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
