// Code generated by entc, DO NOT EDIT.

package list

import (
	"time"
)

const (
	// Label holds the string label denoting the list type in the database.
	Label = "list"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldThemeID holds the string denoting the theme_id field in the database.
	FieldThemeID = "theme_id"
	// FieldIsDeleted holds the string denoting the is_deleted field in the database.
	FieldIsDeleted = "is_deleted"
	// FieldLastModified holds the string denoting the last_modified field in the database.
	FieldLastModified = "last_modified"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTheme holds the string denoting the theme edge name in mutations.
	EdgeTheme = "theme"
	// EdgeTasks holds the string denoting the tasks edge name in mutations.
	EdgeTasks = "tasks"
	// Table holds the table name of the list in the database.
	Table = "list"
	// ThemeTable is the table that holds the theme relation/edge.
	ThemeTable = "list"
	// ThemeInverseTable is the table name for the Theme entity.
	// It exists in this package in order to avoid circular dependency with the "theme" package.
	ThemeInverseTable = "theme"
	// ThemeColumn is the table column denoting the theme relation/edge.
	ThemeColumn = "theme_id"
	// TasksTable is the table that holds the tasks relation/edge.
	TasksTable = "task"
	// TasksInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TasksInverseTable = "task"
	// TasksColumn is the table column denoting the tasks relation/edge.
	TasksColumn = "list_id"
)

// Columns holds all SQL columns for list fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldThemeID,
	FieldIsDeleted,
	FieldLastModified,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsDeleted holds the default value on creation for the "is_deleted" field.
	DefaultIsDeleted bool
	// DefaultLastModified holds the default value on creation for the "last_modified" field.
	DefaultLastModified time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt time.Time
)
