// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// List is the predicate function for list builders.
type List func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// Theme is the predicate function for theme builders.
type Theme func(*sql.Selector)
